var data = {"nodes":[
    {"name":"Ingredient 0", "id":0},
    {"name":"Ingredient 1", "id":1},
    {"name":"Ingredient 2", "id":2},
    {"name":"Ingredient 3", "id":3},
    {"name":"Ingredient 4", "id":4},
    {"name":"Ingredient 5", "id":5},
    {"name":"Ingredient 6", "id":6},
    {"name":"Ingredient 7", "id":7},
    {"name":"Ingredient 8", "id":8},
    {"name":"Ingredient 9", "id":9},
    {"name":"Price 10", "id":10},
    {"name":"Price 11", "id":11},
    {"name":"Price 12", "id":12},
    {"name":"Price 13", "id":13},
    {"name":"Price 14", "id":14},
    {"name":"Price 15", "id":15},
    {"name":"Price 16", "id":16},
    {"name":"Price 17", "id":17},
    {"name":"Price 18", "id":18},
    {"name":"Price 19", "id":19},
    ],"links":[
        {"source":0,"target":10,"value":200, "endValue": 10},
        {"source":1,"target":11,"value":234, "endValue": 94},
        {"source":2,"target":12,"value":80, "endValue": 800},
        {"source":3,"target":13,"value":30, "endValue": 300},
        {"source":4,"target":14,"value":200, "endValue": 20},
        {"source":5,"target":15,"value":100, "endValue": 100},
        {"source":6,"target":16,"value":50, "endValue": 50},
        {"source":7,"target":17,"value":400, "endValue": 2},
        {"source":8,"target":18,"value":2, "endValue": 1},
        {"source":9,"target":19,"value":50, "endValue": 50},
    ]}